# Generated by Django 6.0 on 2025-12-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETLHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('running', 'Running')], default='running', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ETL History',
                'verbose_name_plural': 'ETL History',
                'ordering': ['-run_date'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('ofc_name', models.CharField(blank=True, max_length=200)),
                ('xlc_operation', models.CharField(db_index=True, max_length=200)),
                ('dt_end_cli_work_week', models.DateField(db_index=True)),
                ('work_date', models.DateField(blank=True, null=True)),
                ('date_range', models.CharField(blank=True, max_length=100)),
                ('applicant_id', models.CharField(db_index=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('employee_type_id', models.CharField(blank=True, max_length=50)),
                ('shift_number', models.CharField(blank=True, max_length=20)),
                ('bu_dept_name', models.CharField(blank=True, max_length=200)),
                ('allocation_method', models.CharField(blank=True, max_length=100)),
                ('dt_time_start', models.DateTimeField(blank=True, null=True)),
                ('dt_time_end', models.DateTimeField(blank=True, null=True)),
                ('reg_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ot_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('dt_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('hol_wrk_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('clock_in_local', models.CharField(blank=True, max_length=100)),
                ('clock_in_tries', models.IntegerField(default=1)),
                ('clock_in_method', models.CharField(blank=True, max_length=50)),
                ('clock_out_local', models.CharField(blank=True, max_length=100)),
                ('clock_out_tries', models.IntegerField(default=1)),
                ('clock_out_method', models.CharField(blank=True, max_length=50)),
                ('entry_type', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Time Entry',
                'verbose_name_plural': 'Time Entries',
                'ordering': ['-dt_end_cli_work_week', 'xlc_operation'],
                'indexes': [models.Index(fields=['year', 'dt_end_cli_work_week'], name='core_timeen_year_14be2f_idx'), models.Index(fields=['xlc_operation', 'entry_type'], name='core_timeen_xlc_ope_d9982d_idx')],
            },
        ),
    ]
