# Generated by Django 6.0 on 2025-12-06 02:46

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.upload_to_path)),
                ('file_type', models.CharField(choices=[('csv', 'CSV File'), ('excel', 'Excel File')], default='csv', max_length=10)),
                ('year', models.IntegerField(help_text='Year for this data (e.g., 2025)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('replace_existing', models.BooleanField(default=True, help_text='Replace existing data for this year (recommended to avoid duplicates)')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Upload',
                'verbose_name_plural': 'Data Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
