# Generated by Django 6.0 on 2025-12-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_dataupload_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='week_number',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='week_year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['week_year', 'week_number'], name='core_timeen_week_ye_15df6d_idx'),
        ),
    ]
